
services:
  css_alice:
    image: solidproject/community-server:7
    environment:
      - CSS_PORT=3000
    ports:
      - 3000:3000

  css_anon:
    image: solidproject/community-server:7
    environment:
      - CSS_PORT=3001
    ports:
      - 3001:3001

  css_recruiter:
    image: solidproject/community-server:7
    environment:
      - CSS_PORT=3002
    ports:
      - 3002:3002


  css_university:
    image: solidproject/community-server:7
    environment:
      - CSS_PORT=3003
    ports:
      - 3003:3003

  css_government:
    image: solidproject/community-server:7
    environment:
      - CSS_PORT=3004
    ports:
      - 3004:3004
