
services:
  css_alice:
    profiles:
      - all
      - components
      - usecases
    image: solidproject/community-server:7
    environment:
      - CSS_PORT=${CSS_PORT_ALICE}
      - CSS_SHOW_STACK_TRACE=${CSS_SHOW_STACK_TRACE}
    ports:
      - ${CSS_PORT_ALICE}:${CSS_PORT_ALICE}
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate http://localhost:${CSS_PORT_ALICE} --spider; then touch healthy.flag; else false; fi"
      interval: 1s
      timeout: 1s
      retries: 100
      start_period: 1s

  css_recruiter:
    profiles:
      - all
      - usecases
    image: solidproject/community-server:7
    environment:
      - CSS_PORT=${CSS_PORT_RECRUITER}
      - CSS_SHOW_STACK_TRACE=${CSS_SHOW_STACK_TRACE}
    ports:
      - ${CSS_PORT_RECRUITER}:${CSS_PORT_RECRUITER}
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate http://localhost:${CSS_PORT_RECRUITER} --spider; then touch healthy.flag; else false; fi"
      interval: 1s
      timeout: 1s
      retries: 100
      start_period: 3s

  css_university:
    profiles:
      - all
      - usecases
    image: solidproject/community-server:7
    environment:
      - CSS_PORT=${CSS_PORT_UNIVERSITY}
      - CSS_SHOW_STACK_TRACE=${CSS_SHOW_STACK_TRACE}
    ports:
      - ${CSS_PORT_UNIVERSITY}:${CSS_PORT_UNIVERSITY}
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate http://localhost:${CSS_PORT_UNIVERSITY} --spider; then touch healthy.flag; else false; fi"
      interval: 1s
      timeout: 1s
      retries: 100
      start_period: 3s

  css_government:
    profiles:
      - all
      - usecases
    image: solidproject/community-server:7
    environment:
      - CSS_PORT=${CSS_PORT_GOVERNMENT}
      - CSS_SHOW_STACK_TRACE=${CSS_SHOW_STACK_TRACE}
    ports:
      - ${CSS_PORT_GOVERNMENT}:${CSS_PORT_GOVERNMENT}
    healthcheck:
      test: "[ -e healthy.flag ] || if wget --no-check-certificate http://localhost:${CSS_PORT_GOVERNMENT} --spider; then touch healthy.flag; else false; fi"
      interval: 1s
      timeout: 1s
      retries: 100
      start_period: 3s

