p01: "An overview of limitations and approaches in identity management"
p02: "A Survey of Identity Management for the Future Network" {
  url: https://ieeexplore.ieee.org/document/6275425
  author: "Torres"
  year: 2012
}

p01 --> p02: "cites"