vars: {
  alice: {
    webid: "http://id.be/alice"
    idp: "http://id.be/"
    pod: "http://storage.be/alice"
    password: "*****"
    ssn: "123-45-6789"
    eid: {
      public_key: "f3g5h789"
      secret_key: "abcdefghi"
    }
  }
  pseudo: {
    webid: "http://pseudo.id/hi"
    idp: "http://pseudo.id/"
    password: "*****"
    did: "did:key:z6MkqQ7"
  }
  recruiter: {
    webid: "http://recruiter.be/"
  }
}