direction: down
# t_http: |md
# Transport: HTTP
# | {
#   h: holder
#   v: verifier
#   h -> v: Request
#   v -> h: Response

# }

# t_didcomm: |md
# Transport: DIDComm
# | {
#   h: holder
#   v: verifier
#   i: intermediary
#   h <-> i: Message
#   i <-> v: Message

# }

todo_name: |md
TODO: name
| {
  h: holder
  v: verifier
  
  w: wallet
  wa: wallet agent
  c: client application

  transport_mechanisms: "Transport mechanisms" {
    tx_http: "HTTP"

    tx_didcomm: "DIDComm\n(transport-agnostic)"
  }

  credential_exchange_mechanisms: "Credential exchange mechanisms" {
    cx_presentation_exchange: |md
    [Presentation Exchange](https://identity.foundation/presentation-exchange/spec/v2.0.0)
    |

    cx_vc_api: |md
      [VC-API](https://w3c-ccg.github.io/vc-api/) (HTTP)
    |
  }


  
  w -- wa
  wa -- c: |md
  Verifiable Presentation Request v0.2
  <https://w3c-ccg.github.io/vp-request-spec/>
  |
  c -- h
  h -- transport_mechanisms -- v
  h -- credential_exchange_mechanisms --v


}