vars: {
  alice: {
    webid: "http://id.be/alice"
    idp: "http://id.be/"
    pod: "http://storage.be/alice"
    password: "*****"
  }
  anon: {
    webid: "http://anon.id/hi"
    idp: "http://anon.id/"
    password: "*****"
  }
  recruiter: {
    webid: "http://recruiter.be/"
  }
}

VC01: {
  shape: sql_table
  webid: ${alice.webid}
  identifier: "123456789"
  birth_date: "1990-01-01"
  gender: "F"
}

VC02: {
  shape: sql_table
  degree: "Msc. Physics"
  graduation_date: "2020-06-30"
  grade: "Distinction"
  university: "Ghent University"
}

seq: "Third-party Service solution" {
  shape: sequence_diagram
  alice
  anonymizer
  recruiter: "Recruiter\n${recruiter.webid}"
  pod_alice: Pod Alice\n${alice.pod}
  idp_alice: IDP Alice\n${alice.idp}
  idp_anon: IDP Anon\n${anon.idp}

  pod_alice."Contains VC01 and VC02"  
  

  register_anon: "Register anonymous account" {
    alice -> anonymizer: "Register"
    anonymizer -> idp_anon: "Create anonymous account for Alice"
    idp_anon -> anonymizer: "Account created (WebID: ${anon.webid})"
  }

  setup_auth_tokens: "Setup authentication tokens" {
    auth_alice: "Authenticate: Alice" {
      anonymizer -> idp_alice: "Authenticate(${alice.webid}, ${alice.password})"
      idp_alice -> anonymizer: Token-A
    }
  
    auth_anon: "Authenticate: Anon" {
      anonymizer -> idp_anon: "Authenticate(${anon.webid}, ${anon.password})"
      idp_anon -> anonymizer: Token-X
    }
  }
  
  ctx_anon: "Authenticated as Anon" {
    anonymizer -> recruiter: "Get Presentation Request (Diploma)"
    recruiter -> anonymizer: "Presentation Request (Diploma)"
  }

  ctx_alice: "Authenticated as Alice" {
    anonymizer -> pod_alice: "Fetch diploma VC"
    pod_alice -> anonymizer: "VC01"
  }

  ctx_anon2: "Authenticated as Anon" {
    diploma_exchange: "Diploma Exchange" {
      anonymizer.|
        1. Derive: dVC01 = SelectiveDisclosure(VC01, {degree})
        2. Create Presentation: VP01 = [ dVC01 ]
        3. Sign VP01
      |
      
      anonymizer -> recruiter: "Present VP01"
      recruiter."Verify VP01"
      recruiter -> anonymizer: "Response: RVP01"
    }

    identity_verification: "Identity Verification" {
      # Presentation Request: Identity
      anonymizer -> idp_alice: "Get Presentation Request (Identity)"
      idp_alice -> anonymizer: "Presentation Request (Identity)"

      # Create VP02
      anonymizer -> pod_alice: "Fetch identity VC"
      pod_alice -> anonymizer: "VC02"
      anonymizer.|
        1. Derive: dVC02 = SelectiveDisclosure(VC02, {WebID})
        2. Create Presentation: VP02 = [ dVC02 ]
        3. Sign VP02
      |

      # Exchange VP02
      anonymizer -> recruiter: "Present VP02"
      recruiter."Verify VP02"
      recruiter -> anonymizer: "Response: RVP02"
    }

  }
    

  

}